# Generated by Django 3.0.1 on 2020-01-02 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='choice2',
            new_name='Choice1',
        ),
    ]
