# Generated by Django 3.0.1 on 2020-01-02 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0002_auto_20200102_1941'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice1',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
