# Generated by Django 3.0.1 on 2020-01-02 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0004_choice_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='Choice1',
        ),
    ]
